spring:
    application:
        name:task-service

    # Database Properties
    datasource:
        url: jdbc:postgresql://localhost:5432/taskservice
        username: postgres
        password: '123456'
        driver-class-name: org.postgresql.Driver


    jpa:
        defer-datasource-initialization: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        # Hibernate ddl auto (create, create-drop, validate, update)
        hibernate:
            ddl-auto: create
            show-sql: true


